
# NumPy ve TensorFlow ile Temel İşlemler

Bu notebook'ta, tensör işlemlerini gerçekleştirmek için iki popüler kütüphaneyi keşfedeceğiz:
- **NumPy:** Python'da sayısal hesaplamalar için bir kütüphane.
- **TensorFlow:** Makine öğrenimi için uçtan uca açık kaynaklı bir platform.

İçerik:
1. Tensör oluşturma
2. Temel işlemler (toplama, çarpma, yeniden şekillendirme)
3. TensorFlow ile gradyan hesaplamaları



## 1. NumPy ile Tensör İşlemleri

NumPy, tensör işlemleri için güçlü bir kütüphanedir. Aşağıda, NumPy kullanarak tensörlerin oluşturulması ve manipüle edilmesine yönelik bazı örnekler verilmiştir.


In [1]:
import warnings
warnings.filterwarnings("ignore")

import numpy as np

# Önce tensör oluşturalım
tensor_1 = np.array([[1, 2], [3, 4]])
tensor_2 = np.array([[5, 6], [7, 8]])

print("Tensor 1:")
print(tensor_1)

print("\nTensor 2:")
print(tensor_2)

Tensor 1:
[[1 2]
 [3 4]]

Tensor 2:
[[5 6]
 [7 8]]


In [2]:
# Toplama
added_tensors = tensor_1 + tensor_2
print("\Toplam Tensörü:")
print(added_tensors)

\Toplam Tensörü:
[[ 6  8]
 [10 12]]


In [3]:
# Eleman bazlı çarpım
multiplied_tensors = tensor_1 * tensor_2
print("\Eleman Bazlı Çarpım Tensörü:")
print(multiplied_tensors)

\Eleman Bazlı Çarpım Tensörü:
[[ 5 12]
 [21 32]]


In [4]:
# Matris çarpımı
matmul_tensors = np.dot(tensor_1, tensor_2)
print("\nMatris Çarpımı:")
print(matmul_tensors)


Matris Çarpımı:
[[19 22]
 [43 50]]


**Matris Çarpımı**
İlk satır, ilk matrisin (tensor_1) satırları ile ikinci matrisin (tensor_2) sütunları çarpılır:
* (1×5)+(2×7)=5+14=19(1×5)+(2×7)=5+14=19
* (1×6)+(2×8)=6+16=22(1×6)+(2×8)=6+16=22

İkinci satır için:
* (3×5)+(4×7)=15+28=43(3×5)+(4×7)=15+28=43
* (3×6)+(4×8)=18+32=50(3×6)+(4×8)=18+32=50

In [5]:
# Reshaping a tensor
reshaped_tensor = tensor_1.reshape(4, 1)
print("\nReshaped Tensor:")
print(reshaped_tensor)


Reshaped Tensor:
[[1]
 [2]
 [3]
 [4]]



## 2. TensorFlow ile Tensör İşlemleri

TensorFlow, tensör hesaplamaları için araçlar sağlar. Aşağıda, TensorFlow kullanılarak gerçekleştirilen temel işlemlere bazı örnekler verilmiştir.


In [7]:

import tensorflow as tf

# Creating tensors
tensor_a = tf.constant([[1, 2], [3, 4]], dtype=tf.float32)
tensor_b = tf.constant([[5, 6], [7, 8]], dtype=tf.float32)

print("Tensor A:")
print(tensor_a)

print("\nTensor B:")
print(tensor_b)

Tensor A:
tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)

Tensor B:
tf.Tensor(
[[5. 6.]
 [7. 8.]], shape=(2, 2), dtype=float32)


In [8]:
# Toplama
added_tensors_tf = tf.add(tensor_a, tensor_b)
print("\Toplama Tensörü (TensorFlow):")
print(added_tensors_tf)

\Toplama Tensörü (TensorFlow):
tf.Tensor(
[[ 6.  8.]
 [10. 12.]], shape=(2, 2), dtype=float32)


In [9]:
# Eleman bazlı çarpım
multiplied_tensors_tf = tf.multiply(tensor_a, tensor_b)
print("\nEleman Bazlı Çarpım Tensörü (TensorFlow):")
print(multiplied_tensors_tf)


Eleman Bazlı Çarpım Tensörü (TensorFlow):
tf.Tensor(
[[ 5. 12.]
 [21. 32.]], shape=(2, 2), dtype=float32)


In [10]:
# Matris Çarpımı
matmul_tensors_tf = tf.matmul(tensor_a, tensor_b)
print("\nMatris Çarpım Tensörü (TensorFlow):")
print(matmul_tensors_tf)


Matris Çarpım Tensörü (TensorFlow):
tf.Tensor(
[[19. 22.]
 [43. 50.]], shape=(2, 2), dtype=float32)


In [11]:
# Gradient hesaplama
with tf.GradientTape() as tape:
    tape.watch(tensor_a)
    result = tf.reduce_sum(tensor_a * tensor_a)
gradient = tape.gradient(result, tensor_a)
print("\nKarelerin türev toplamları:")
print(gradient)


Karelerin türev toplamları:
tf.Tensor(
[[2. 4.]
 [6. 8.]], shape=(2, 2), dtype=float32)



## Sonuç

Bu notebook'ta, NumPy ve TensorFlow kullanarak temel tensör işlemlerini inceledik. Bu araçlar, makine öğrenimi ve derin öğrenmedeki daha ileri düzey hesaplamalar için temel oluşturur. Özellikle TensorFlow'un gradyan hesaplayabilme yeteneği, sinir ağlarının oluşturulması ve eğitimi açısından oldukça güçlüdür.

Daha fazla öğrenmek için:
- [NumPy dökümantasyonuna](https://numpy.org/doc/) göz atabilirsiniz.
- [TensorFlow eğitimlerine](https://www.tensorflow.org/tutorials) göz atabilirsiniz.
